# Generated by Django 5.2.11 on 2026-02-26 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price before discount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Moderation"),
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("blocked", "Blocked"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_premium", models.BooleanField(db_index=True, default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("favorites_count", models.PositiveIntegerField(default=0)),
                (
                    "login_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("username", "Username"),
                            ("social", "Social Media"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("account_email", models.TextField(blank=True, default="", help_text="Encrypted")),
                (
                    "account_password",
                    models.TextField(blank=True, default="", help_text="Encrypted"),
                ),
                ("account_additional_info", models.JSONField(blank=True, default=dict)),
                ("level", models.CharField(blank=True, default="", max_length=50)),
                ("rank", models.CharField(blank=True, default="", max_length=50)),
                ("skins_count", models.PositiveIntegerField(default=0)),
                ("features", models.JSONField(blank=True, default=list)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="games.game",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
                "db_table": "listings",
                "ordering": ["-is_premium", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="marketplace.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "db_table": "favorites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/%Y/%m/")),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="marketplace.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Image",
                "verbose_name_plural": "Listing Images",
                "db_table": "listing_images",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ListingView",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_views",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing View",
                "verbose_name_plural": "Listing Views",
                "db_table": "listing_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["seller", "status"], name="listings_seller__9c3ec9_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["game", "status", "created_at"], name="listings_game_id_3b9b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status", "is_premium"], name="listings_status_4063e0_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price"], name="listings_price_e6fc4f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "listing")},
        ),
    ]
