# Generated by Django 5.2.11 on 2026-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_warranty_sale_promo_savedsearch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="discount_fixed",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="min_purchase",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=15, null=True
            ),
        ),
    ]
