# Generated by Django 5.2.11 on 2026-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_promocode_discount_fixed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="video_file_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Telegram file_id for uploaded video",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="video_upload_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="One-time token for video upload via Telegram bot",
                max_length=64,
            ),
        ),
    ]
