# Generated by Django 5.2.11 on 2026-03-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_add_video_fields_to_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="video_rejected_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason for video rejection (shown to seller)"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="video_status",
            field=models.CharField(
                choices=[
                    ("none", "No video"),
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="none",
                help_text="Admin moderation status for video",
                max_length=20,
            ),
        ),
    ]
