# Generated by Django 5.2.11 on 2026-03-27 10:23

from django.db import migrations, models


def populate_listing_codes(apps, schema_editor):
    """Assign WB-1001, WB-1002, ... to existing listings ordered by created_at."""
    Listing = apps.get_model("marketplace", "Listing")
    listings = Listing.objects.filter(listing_code="").order_by("created_at")
    num = 1001
    for listing in listings:
        listing.listing_code = f"WB-{num}"
        num += 1
    Listing.objects.bulk_update(listings, ["listing_code"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_add_video_status_fields"),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name="listing",
            name="listing_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Auto-generated unique listing code (e.g. WB-1001)",
                max_length=10,
            ),
        ),
        # Step 2: Populate existing listings
        migrations.RunPython(populate_listing_codes, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="listing",
            name="listing_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Auto-generated unique listing code (e.g. WB-1001)",
                max_length=10,
                unique=True,
            ),
        ),
    ]
