# Generated by Django 5.2.11 on 2026-03-27 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_image"),
        ("marketplace", "0006_add_listing_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                choices=[("sell", "Sell"), ("rent", "Rent")],
                db_index=True,
                default="sell",
                help_text="sell = sotish, rent = ijarada berish",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rental_deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kafolat depozit summasi (akkaunt qaytarilmasa ushlanadi)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rental_period_days",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Ijara muddati (kun): 1, 3, 7, 14, 30", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rental_price_per_day",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kunlik ijara narxi",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["listing_type", "status"], name="listings_listing_56bbe5_idx"
            ),
        ),
    ]
