# Generated by Django 5.2.11 on 2026-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_add_rental_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="rental_time_slots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Foydalanuvchi belgilagan vaqt/narx variantlari (max 5 ta)",
            ),
        ),
    ]
