# Generated by Django 5.2.11 on 2026-03-27 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_add_rental_time_slots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingPromotion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hours", models.PositiveIntegerField(help_text="Promotion duration in hours")),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per hour at time of purchase",
                        max_digits=15,
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Discount applied (e.g. 10, 20, 30)"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount charged", max_digits=15
                    ),
                ),
                ("starts_at", models.DateTimeField(help_text="When promotion starts")),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, help_text="When promotion expires"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listing_promotions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "is_active", "expires_at"],
                        name="listing_pro_listing_b85c4c_idx",
                    )
                ],
            },
        ),
    ]
