# Generated by Django 5.2.11 on 2026-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_add_listing_promotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="login_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("username", "Username"),
                    ("social", "Social Media"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
