# Generated by Django 5.2.11 on 2026-03-27 18:11

from django.db import migrations, models


def empty_strings_to_null(apps, schema_editor):
    """Convert empty listing_code strings to NULL before adding nullable unique constraint."""
    Listing = apps.get_model("marketplace", "Listing")
    updated = Listing.objects.filter(listing_code="").update(listing_code=None)
    if updated:
        print(f"  Converted {updated} empty listing_codes to NULL")


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_expand_login_method_choices"),
    ]

    operations = [
        # Step 1: Convert empty strings to NULL (otherwise unique constraint fails)
        migrations.RunPython(empty_strings_to_null, migrations.RunPython.noop),
        # Step 2: Make field nullable
        migrations.AlterField(
            model_name="listing",
            name="listing_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated unique listing code (e.g. WB-1001)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
