# Generated by Django 5.2.11 on 2026-03-28 18:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_add_boost_fields_spamfilter_pricewatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price before discount",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="rental_deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kafolat depozit summasi (akkaunt qaytarilmasa ushlanadi)",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="rental_price_per_day",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kunlik ijara narxi",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="pricewatch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="spamfilter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
