# Generated by Django 5.2.11 on 2026-03-23 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_depositrequest_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="buyer_cancel_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="buyer_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="buyer_cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="buyer_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="buyer_confirmed_at_trade",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="buyer_telegram_message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="seller_cancel_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="seller_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="seller_cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="seller_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="seller_confirmed_at_trade",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="seller_telegram_message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UZS", max_length=10)),
                ("card_number", models.CharField(max_length=20)),
                ("card_holder_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("humo", "HUMO"),
                            ("uzcard", "UZCARD"),
                            ("visa", "VISA"),
                            ("mastercard", "MasterCard"),
                        ],
                        default="humo",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("processing", "Jarayonda"),
                            ("completed", "Bajarildi"),
                            ("rejected", "Rad etildi"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("user_telegram_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pul yechish so'rovi",
                "verbose_name_plural": "Pul yechish so'rovlari",
                "db_table": "withdrawal_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
