# Generated by Django 5.2.11 on 2026-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_escrowtransaction_buyer_cancel_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="trade_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique trade verification code for admin tracking",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
