# Generated by Django 5.2.11 on 2026-03-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_backfill_trade_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("purchase", "Purchase"),
                    ("refund", "Refund"),
                    ("commission", "Commission"),
                    ("subscription", "Subscription"),
                    ("promotion", "Promotion"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
