# Generated by Django 5.2.11 on 2026-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(
                blank=True, help_text="O'yin rasmi (banner)", null=True, upload_to="games/"
            ),
        ),
    ]
